// Generated by https://quicktype.io

export interface CityType {
    id: number;
    provinsi: Provinsi;
    kota: string;
    kecamatan: string;
    kelurahan: string;
    postal_code: number;
    created_at: null;
    updated_at: null;
}

export enum Provinsi {
    Bali = "Bali",
    JawaBarat = "Jawa Barat",
}
