// Generated by https://quicktype.io

export interface NewsType {
    id: number;
    category_news_id: number;
    user_id: number;
    title: string;
    slug: string;
    desc: string;
    body: string;
    views: number;
    image: string;
    created_at: Date;
    updated_at: Date;
    category_news: CategoryNews;
    user: User;
}

export interface CategoryNews {
    id: number;
    title: string;
    slug: string;
    created_at: Date;
    updated_at: Date;
}

export interface User {
    id: number;
    name: string;
    email: string;
    phone: null;
    address: null;
    store: null;
    gender: null;
    role: null;
    image: null;
    created_at: Date;
    updated_at: Date;
}
