// Generated by https://quicktype.io

export interface ServiceRateType {
    id: number;
    shipping_service_id: number;
    shipping_zone_id: number;
    price_per_kg: number;
    price_per_volume: number;
    min_price: number;
    estimation_days_min: number;
    estimation_days_max: number;
    created_at: Date;
    updated_at: Date;
    shipping_service: ShippingService;
    shipping_zone: ShippingZone;
}

export interface ShippingService {
    id: number;
    name: string;
    desc: string;
    price: number;
    is_active: number;
    created_at: Date;
    updated_at: Date;
}

export interface ShippingZone {
    id: number;
    origin_city_id: number;
    destination_city_id: number;
    distance_km: number;
    created_at: Date;
    updated_at: Date;
    origin_city: NCity;
    destination_city: NCity;
}

export interface NCity {
    id: number;
    provinsi: string;
    kota: string;
    kecamatan: string;
    kelurahan: string;
    postal_code: number;
    created_at: null;
    updated_at: null;
}
