// Generated by https://quicktype.io

export interface ShippingServiceType {
    id: number;
    name: string;
    desc: string;
    price: number;
    is_active: number;
    created_at: Date;
    updated_at: Date;
}
