// Generated by https://quicktype.io

export interface ShippingZoneType {
    id: number;
    origin_city_id: number;
    destination_city_id: number;
    distance_km: number;
    created_at: Date;
    updated_at: Date;
    origin_city: NCity;
    destination_city: NCity;
}

export interface NCity {
    id: number;
    provinsi: string;
    kota: string;
    kecamatan: string;
    kelurahan: string;
    postal_code: number;
    created_at: null;
    updated_at: null;
}
