// Generated by https://quicktype.io

export interface UserType {
    id: number;
    name: string;
    email: string;
    phone: string | null;
    address: string | null;
    city_id: number | null;
    store: string | null;
    gender: string | null;
    vehicle_type: string | null;
    vehicle_number: string | null;
    role: string;
    image: string | null; // as string URL atau path kalau dari backend
    created_at: Date;
    updated_at: Date;
    city: City | null;
}

export interface City {
    id: number;
    provinsi: string;
    kota: string;
    kecamatan: string;
    kelurahan: string;
    postal_code: number;
    created_at: Date | null;
    updated_at: Date | null;
}

// HANYA data yang perlu dikirim lewat form
export type ProfileFormData = {
    name: string;
    email: string;
    phone: number | string;
    address: string;
    city_id: number | string; // penting: hanya city_id, bukan object city
    store: string;
    gender: string;
    vehicle_type: string;
    vehicle_number: string;
    role: string; // kalau role diubah manual, kalau tidak, hapus juga ini
    image: File | null; // file baru upload
    password?: string; // opsional, misal update password
};
