// Generated by https://quicktype.io

export interface UserType {
    id: number;
    name: string;
    email: string;
    phone: string;
    address: string;
    city_id: number;
    store: null;
    gender: string;
    vehicle_type: null;
    vehicle_number: null;
    role: string;
    image: string;
    created_at: Date;
    updated_at: Date;
    warehouse_id: number;
    city: City;
    warehouse: Warehouse;
}

export interface City {
    id: number;
    provinsi: string;
    kota: string;
    kecamatan: string;
    kelurahan: string;
    postal_code: number;
    created_at: null;
    updated_at: null;
}

export interface Warehouse {
    id: number;
    name: string;
    city_id: number;
    manager: string;
    address: string;
    created_at: Date;
    updated_at: Date;
    city: City;
}

// HANYA data yang perlu dikirim lewat form
export type ProfileFormData = {
    name: string;
    email: string;
    phone: number | string;
    address: string;
    city_id: string; // penting: hanya city_id, bukan object city
    store: string;
    gender: string;
    vehicle_type: string;
    vehicle_number: string;
    warehouse_id: string;
    role: string; // kalau role diubah manual, kalau tidak, hapus juga ini
    image: File | null; // file baru upload
    password?: string; // opsional, misal update password
};
