// Generated by https://quicktype.io

export interface UserType {
    id: number;
    name: string;
    email: string;
    phone: null | string;
    address: null | string;
    city_id: number | null;
    store: null | string;
    gender: null | string;
    vehicle_type: null | string;
    vehicle_number: null | string;
    role: string;
    image: null;
    created_at: Date;
    updated_at: Date;
    city: City | null;
}

export interface City {
    id: number;
    provinsi: string;
    kota: string;
    kecamatan: string;
    kelurahan: string;
    postal_code: number;
    created_at: null;
    updated_at: null;
}
