// Generated by https://quicktype.io

export interface WareHouseType {
    id: number;
    name: string;
    city_id: number;
    manager: string;
    address: string;
    created_at: Date;
    updated_at: Date;
    city: City;
}

export interface City {
    id: number;
    provinsi: string;
    kota: string;
    kecamatan: string;
    kelurahan: string;
    postal_code: number;
    created_at: null;
    updated_at: null;
}
